// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // static FirebaseOptions get currentPlatform {
  //   if (kIsWeb) {
  //     return web;
  //   }
  //   // ignore: missing_enum_constant_in_switch
  //   switch (defaultTargetPlatform) {
  //     case TargetPlatform.android:
  //       return android;
  //     case TargetPlatform.iOS:
  //       return ios;
  //     case TargetPlatform.macOS:
  //       return macos;
  //   }

  //   throw UnsupportedError(
  //     'DefaultFirebaseOptions are not supported for this platform.',
  //   );
  // }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyALsOIlKAwYTivmAWOxWqlhgp1PyGhO0Zg",
      authDomain: "lectfai.firebaseapp.com",
      projectId: "lectfai",
      storageBucket: "lectfai.appspot.com",
      messagingSenderId: "294198838372",
      appId: "1:294198838372:web:f595fceafdfd322f9b0b71",
      measurementId: "G-KEDSN0H1XN"
      // apiKey: 'xxxxxxxxxxxxxxxxxxx',
      // appId: 'xxxxxxxxxxxxxxxxxxx',
      // messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
      // projectId: 'xxxxxxxxxxxxxxxxxxx',
      // authDomain: 'xxxxxxxxxxxxxxxxxxx',
      // databaseURL: 'xxxxxxxxxxxxxxxxxxx',
      // storageBucket: 'xxxxxxxxxxxxxxxxxxx',
      // measurementId: 'xxxxxxxxxxxxxxxxxxx',
      // Import the functions you need from the SDKs you need
// import { initializeApp } from "firebase/app";
// // TODO: Add SDKs for Firebase products that you want to use
// // https://firebase.google.com/docs/web/setup#available-libraries

// // Your web app's Firebase configuration
// const firebaseConfig = {
//   apiKey: "AIzaSyALsOIlKAwYTivmAWOxWqlhgp1PyGhO0Zg",
//   authDomain: "lectfai.firebaseapp.com",
//   projectId: "lectfai",
//   storageBucket: "lectfai.appspot.com",
//   messagingSenderId: "294198838372",
//   appId: "1:294198838372:web:f595fceafdfd322f9b0b71"
// };

// // Initialize Firebase
// const app = initializeApp(firebaseConfig);
      );
}
